FROM node:10
RUN git clone https://github.com/kaedmond24/containerized_ecommerce_application.git
WORKDIR containerized_ecommerce_application/frontend
EXPOSE 3000
RUN npm install --save-dev @babel/plugin-proposal-private-property-in-object
RUN npm install
CMD npm run build
